// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZR4hfpaGZHpz83Yf9jy2OnNJV65ovdYQ',
    appId: '1:862202346549:web:bcf6587d1c8a31939ac57c',
    messagingSenderId: '862202346549',
    projectId: 'fir-teste-1b0a3',
    authDomain: 'fir-teste-1b0a3.firebaseapp.com',
    storageBucket: 'fir-teste-1b0a3.appspot.com',
    measurementId: 'G-KKEW4PQWXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNckPEmiuPg6edqkB9NUB1h6TgQ_EHKSA',
    appId: '1:862202346549:android:081df28750d45fa29ac57c',
    messagingSenderId: '862202346549',
    projectId: 'fir-teste-1b0a3',
    storageBucket: 'fir-teste-1b0a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABAIc-lTipHt5Gg8YB7HeF3MlM8nVaZkE',
    appId: '1:862202346549:ios:04bd79283c6b8cee9ac57c',
    messagingSenderId: '862202346549',
    projectId: 'fir-teste-1b0a3',
    storageBucket: 'fir-teste-1b0a3.appspot.com',
    iosClientId: '862202346549-4h0ibdnc3tvhg72o2vuke56b1d2b3v7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTeste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABAIc-lTipHt5Gg8YB7HeF3MlM8nVaZkE',
    appId: '1:862202346549:ios:04bd79283c6b8cee9ac57c',
    messagingSenderId: '862202346549',
    projectId: 'fir-teste-1b0a3',
    storageBucket: 'fir-teste-1b0a3.appspot.com',
    iosClientId: '862202346549-4h0ibdnc3tvhg72o2vuke56b1d2b3v7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTeste',
  );
}
